name: Standard Node Deployment
# Allows manually running a workflow
# Normally would use different triggers depending on context
# Here we just want a manual trigger
on: [workflow_dispatch]
jobs:
  sast:
    runs-on: ubuntu-latest
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Run the "semgrep ci" command on the command line of the docker image.
      - name: Configure semgrep
        run: semgrep --config=auto
      - name: Run Static Application Analysis
        run: semgrep ci --subdir=gh-node/
        env:
          # Connect to Semgrep AppSec Platform through your SEMGREP_APP_TOKEN.
          # Generate a token from Semgrep AppSec Platform > Settings
          # and add it to your GitHub secrets.
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        # We can set the directory this pipeline is working with via this
        # Otherwise we'd have to specify in every step
        working-directory: ./gh-node 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0 # There's probably a better way to do this using a specific version in the app code directory
      - name: Build
        run: npm ci \
             npm run build
      - name: Test
        run: npm test
