name: Standard Node Deployment
# Allows manually running a workflow
# Normally would use different triggers depending on context
# Here we just want a manual trigger
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        # We can set the directory this pipeline is working with via this
        # Otherwise we'd have to specify in every step
        working-directory: ./gh-node 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Build
        run: npm ci \
             npm run build
      - name: Test
        run: npm test
